### ISSUE TITLE
Not uploading images

### ISSUE THREAD

**Issue by adrianoqpchikande** [hvlads/django-ckeditor-5#10]
Opens dialog to select file from PC but fails to load it into the editor. Any fix ?
![image](https://user-images.githubusercontent.com/63517784/85088487-8a577700-b1e0-11ea-8114-56d521ea9fb3.png)

**Comment by 5no0p** [comment]
did u put `re_path(r'^(?:.*)/?$',...)` in your urlpatterns? like:
`re_path(r'^(?:.*)/?$', include('frontend.urls'))`
