### ISSUE TITLE
Working only with ModelForm

### ISSUE THREAD

**Issue by SaidLutfullin** [hvlads/django-ckeditor-5#103]
It doesn't work with simple forms, only woth ModelForm, does it?

**Comment by hvlads** [comment]
You can use  the [CKEditor5Widget](https://github.com/hvlads/django-ckeditor-5/blob/b5e0d5df819ffd6229e5ecf859e75109a8d9b975/django_ckeditor_5/widgets.py-#L18) 

https://docs.djangoproject.com/en/4.1/ref/forms/widgets/
