### ISSUE TITLE
Is django-ckeditor-5 Just for Django admin ?

### ISSUE THREAD

**Issue by anugrahsoft** [hvlads/django-ckeditor-5#104]
Hi,

I've been fighting the package for a day, but without luck to display a text area in the front end (I render the fields manually like {{ form.text }} ) but if you just put {{ form }} all ckeditor5 text field will render.

I'm not talking about django admin.

Now my question is : does this package render manual fields like {{ form.field }} in Django front-end templates (excluding django admin) ?

thank you.

**Comment by hvlads** [comment]
Try [this](https://github.com/hvlads/django-ckeditor-5/blob/b5e0d5df819ffd6229e5ecf859e75109a8d9b975/example/blog/articles/forms.py#L8)
