### ISSUE TITLE
django-ckeditor-5 does not handle CSRF_COOKIE_NAME and image upload gives 403 Forbidden (CSRF token missing or incorrect.)

### ISSUE THREAD

**Issue by mpuchko** [hvlads/django-ckeditor-5#107]
Hello

If in Django settings `CSRF_COOKIE_NAME` is changed from 'csrftoken' to some other value, then code in
`django_ckeditor_5\static\django_ckeditor_5\app.js` is not working:
```python
        config['simpleUpload'] = {
            'uploadUrl': upload_url, 'headers': {
                'X-CSRFToken': getCookie('csrftoken'),
            }
        }
```
need to use value from `settings.CSRF_COOKIE_NAME` in this place, not just 'csrftoken'.

The only solution now is turn-off csrf protection for image upload view via csrf_exempt.
But SessionAuthentication in DRF enforces csrf for authenticated requests, so for DRF csrf_exempt does not work.

**Comment by mpuchko** [comment]
for django admin this fix is working for me:

```python
        config['simpleUpload'] = {
            'uploadUrl': upload_url, 'headers': {
                'X-CSRFToken': document.getElementsByName("csrfmiddlewaretoken")[0].value,
//                'X-CSRFToken': getCookie('csrftoken'),
            }
        }

```

**Comment by hvlads** [comment]
This is fixed in the latest version.

**Comment by jsolly** [comment]
THANK YOU!
