### ISSUE TITLE
[Enhancement] Automatically give all headers an id attribute and anchor link

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#110]
## Context 
When I author content in CKEditor (like a blog post), I'd like to have 'anchor links' to generate links that take the user to a specific part of the webpage. This is often done on documentation sites, where the user is brought to a particular part of a page by adding `#<section_name>` to the URL. 

Example:
https://docs.djangoproject.com/en/4.0/#getting-help

## Current Behavior/Workaround
Today, I can do this by going into the CKEditor source and manually adding an `id` attribute to a header.
```html
<h2 id="Introduction">Introduction</h2>
```
But this is very cumbersome, as a single blog post could have dozens of headers.

After adding the `id` to the header, I can use a CSS pseudo selector like `::after` along with a `:hover` to add a paragraph symbol to the right of the header or manually add the anchor link like this:
![image](https://user-images.githubusercontent.com/9572232/209475241-a46051cf-e637-47ee-8e72-4484c3c49159.png)
When a user hovers or focuses on the header, the link symbol appears letting them know they can copy a link to this section.

## Ideal behavior
In the best-case scenario, headers automatically get an `id` attribute when created within CKEditor. They would also automatically get an anchor tag nested inside a symbol like this: 🔗

At a minimum, it would be nice if the `id` was added by default, and I could handle the anchor link with CSS.

### Research
I found a few CKEditor issue pages where people try to do what I am talking about, but I couldn't find a great solution. See:
[Easily add id attributes to elements](https://github.com/ckeditor/ckeditor5/issues/7369)
[Headings with IDs and links](https://github.com/ckeditor/ckeditor5/issues/6815)
[Adding index based on headers in content](https://github.com/ckeditor/ckeditor5/issues/6627)

### Plugin to manually add an id attribute to an element
I found a CKEditor5 plugin called [ckeditor5-add-attribute-to-element](https://github.com/rhysstubbs/ckeditor5-add-attribute-to-element), but this only slightly alleviates the problem by not making me go into the source to add an id. 

## Things to consider
Should the `id` be hard coded at creation time, or would the `id` change if the header text was altered?
Is there any workaround I can follow that doesn't involve a lot of manual source editing?

**Comment by hvlads** [comment]
Hi, I think this is a question for the developers of ckeditor5 or you can write a plugin for this

I don't change the ckeditor5 code and I don't try not to add third-party plugins.

Without changing the code, you could try adding something [like](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuring-custom-heading-elements:~:text=%23-,Configuring,-custom%20heading%20elements):

```
  {
    "model": 'headingFancy',
    "view": {
        "name": 'h2',
        "classes": 'fancy3',
        "attributes": {"id": uuid.uuid4().hex[:6].upper()}
    },
    "title": 'Heading 2 (fancy)',
    "class": 'ck-heading_heading2_fancy',
    "converterPriority": 'high'
  }
```

**Comment by jsolly** [comment]
@hvlads. I am happy to reach out to CKEditor5 team about this. May I ask why you edited your comment to remove the suggested workaround? Did you realize it wouldn't work?

I am also curious why this issue was reopened if it's not possible to accomplish my goal within this repo.

Let me know what I should do next!

**Comment by hvlads** [comment]
Hi, I forgot to close this issue. I think you could solve it through the settings https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuring-custom-heading-elements

but this will create one id for one header
either using a third-party package https://www.npmjs.com/package/ckeditor5-heading-with-id

**Comment by jsolly** [comment]
I wrote some JavaScript to do it on the fly. I added this script to my post-detail page. It adds ids to every header.

I didn't bother adding logic to ensure that header ids didn't have conflicts.
```js
var headers = document.querySelectorAll("h1, h2, h3");
headers.forEach(header => {
  header.id = header.textContent.toLowerCase().replace(/[\s+/[^a-zA-Z0-9_\-]/g, '_');
});
```

Now I simply select text and add a regular URL for the header like this:
![image](https://user-images.githubusercontent.com/9572232/214236925-27d26a3b-3b6d-4588-a665-8f71b533736e.png)

It's still a little manual, but not that bad at all!

**Comment by jsolly** [comment]
Quick update for anyone who might be reading this. I improved the code so that it includes both an id and a link emoji so users can copy it to their clipboard. Here's the code!

```js
function addHeaderIDs() {
  var headers = document.querySelectorAll("h1, h2, h3");
  for (const header of headers) {
    header.id = header.textContent
      .trim()
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-zA-Z0-9_\-]/g, "");
  }
}

function addHeaderLinks() {
  var headers = document.querySelectorAll("h1,h2,h3");
  for (const header of headers) {
    var headerId = header.getAttribute("id");
    var link = document.createElement("a");
    link.href = `#${headerId}`;
    link.classList.add("header-link");
    link.innerHTML = " 🔗";
    header.appendChild(link);
  }
  var links = document.querySelectorAll(".header-link");
  for (const link of links) {
    link.addEventListener("click", function () {
      var linkUrl = this.href;
      navigator.clipboard.writeText(linkUrl).then(
        function () {
          console.log("Link URL copied to clipboard!");
        },
        function (err) {
          console.log("Unable to copy link URL: ", err);
        }
      );
    });
  }
}

document.addEventListener("DOMContentLoaded", function () {
  addHeaderIDs();
  addHeaderLinks();
});
```

All I needed to do was import this file into my post-detail page and it all works.
![2023-01-24_22-51-27 (3)](https://user-images.githubusercontent.com/9572232/214500281-6facbdae-12b2-42fe-94e7-46a5b6a3b190.gif)
