### ISSUE TITLE
Enable word and character count on CKEditor5Fields

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#117]
## Context 
I want to see the current character and word count while editing blog posts.
![image](https://user-images.githubusercontent.com/9572232/213620340-a0573b58-0931-41b9-bd72-429e661ab943.png)

## Ideal behavior
Word and Character count can be enabled by adding a configuration within CKEDITOR_5_CONFIGS.

## Path Forward
I see a [Word count and character count](https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html) in the ckeditor5 docs.

> There are two ways how you can inject the word count statistics into your page:
> 
> By using the [WordCount#wordCountContainer](https://ckeditor.com/docs/ckeditor5/latest/api/module_word-count_wordcount-WordCount.html#member-wordCountContainer) property as shown in the example above.
> 
> By specifying where the word count feature should insert its container which can be done by using [config.wordCount.container](https://ckeditor.com/docs/ckeditor5/latest/api/module_word-count_wordcount-WordCountConfig.html#member-container).

Would either of these methods be the way to implement this?

## Things to consider
It might be nice to enable this on a container-by-container basis, but I am okay if enabling it inserts it into every CKEditor5Field.

I could probably pull this off with JS or HTMX, but it would be great if this could be native within ckeditor5.

**Comment by hvlads** [comment]
Hi, this functionality will appear in the next version

**Comment by jsolly** [comment]
Can you help me figure out how to use this in the Django context? I tried adding this to my settings.py, but nothing is showing up

```python
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            ...,
            "wordCount"
        ],
        "wordCount": {
            "container": "#word-count-container",
            "displayWords": "true",
            "displayCharacters": "true",
        }
    },
    ...
}

```

It would be nice if `container` could match all CKEditor5Fields...I also tried:
```
            "container": ".ck-editor",
```

But that didn't word either. Finally, I tried just:
```
        "wordCount": {"showCharCount": "true"},
 ```
But that didn't work = /

**Comment by jsolly** [comment]
Can you help me figure out how to use this in the Django context? I tried adding this to my settings.py, but nothing is showing up

```python
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            ...,
            "wordCount"
        ],
        "wordCount": {
            "container": "#word-count-container",
            "displayWords": "true",
            "displayCharacters": "true",
        }
    },
    ...
}

```

It would be nice if `container` could match all CKEditor5Fields...I also tried:
```
            "container": ".ck-editor",
```

But that didn't word either. Finally, I tried just:
```
        "wordCount": {"showCharCount": "true"},
 ```
But that didn't work = /

I am using django-ckeditor-5==0.2.3
