### ISSUE TITLE
User ID in the upload path

### ISSUE THREAD

**Issue by jdbit** [hvlads/django-ckeditor-5#12]
Hi,
I would like to change the default upload path and add a user id to the path. I've found the CKEDITOR_5_UPLOADS_FOLDER setting, but is there any way to add a user id to the path, for example, /content/{USER_ID}/?
Thanks!

**Comment by hvlads** [comment]
Hi, you can copy django_ckeditor_5 to the project root folder and override these methods:
https://github.com/hvlads/django-ckeditor-5/blob/0ffa2e0f72fa2f083ca226d254bb5d0a46161f38/django_ckeditor_5/views.py#L40
