### ISSUE TITLE
How do I use the wordCount plugin?

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#121]
Thanks for implementing https://github.com/hvlads/django-ckeditor-5/issues/117. Now, how do I use it?

I tried adding this to my settings.py, but nothing is showing up
```python
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            ...,
            "wordCount"
        ],
        "wordCount": {
            "container": "#word-count-container",
            "displayWords": "true",
            "displayCharacters": "true",
        }
    },
    ...
}
```
It would be nice if the container could match all CKEditor5Fields...I also tried:

            "container": ".ck-editor",
But that didn't word either. Finally, I tried just:

        "wordCount": {"showCharCount": "true"},
But that didn't work = /

I am using django-ckeditor-5==0.2.3

## Notes
Once I figure this out, I can write up a little documentation for it so we can include it in the readme.

I might be wrong to put it in the toolbar. I am just trying different things to see if they work. I don't think this is supposed to be a toolbar item, but simply displays statistics at the bottom of the container.

**Comment by hvlads** [comment]
Hi @jsolly, I installed a new django and django-ckeditor-5 and I see that it works, without additional project settings 😊

![image](https://user-images.githubusercontent.com/10467081/219864121-acc195c1-274c-4177-839e-9b9d89b7e182.png)

**Comment by jsolly** [comment]
I do see the same thing on my Django Admin settings, but the issue for me is that it is not sharing styles in the front-end. For example, in [this issue](https://github.com/hvlads/django-ckeditor-5/issues/78) I had to do some work to get the CKEditor styles to work outside of the admin page. I think I need to do something similar here to get it working outside of the admin page.

I know this package was made for the admin page, but can you think of any reason this wouldn't show up in the front-end?

Here is a quick example of how I am using this library:

Models.py
```py
class Post(models.Model):
    content = CKEditor5Field(blank=True, null=True, config_name="extends")
```

forms.py
```py
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "content",
        )
```
post-create.html (template)
```html
<div class="form-group">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{ form.media }} {{ form.as_p }}
    <button class="btn btn-outline-info" id="post-create-button" type="submit">
      Post
    </button>
    {% endblock content %}
  </form>
</div>
```

**Comment by jsolly** [comment]
So silly, I had CSS that made the text white in the front-end so I just didn't see it 😂
![image](https://user-images.githubusercontent.com/9572232/222328513-5c47b386-5012-49aa-ad69-f7287a7e73e9.png)
