### ISSUE TITLE
Allow uploads for super_users

### ISSUE THREAD

**Issue by sytch** [hvlads/django-ckeditor-5#122]
hi, it would be nice, if users with `is_superuser=True` and `is_staff=False` can upload images. 

views.py
```
def upload_file(request):
    if request.method == "POST" and request.user.is_staff: <-- add super users here
```

**Comment by hvlads** [comment]
Sorry, I didn't understand the problem, now everyone who has access to the django admin panel can upload images, including the superuser, you can also write your own upload logic, see https://github.com/hvlads/django-ckeditor-5/issues/115
