### ISSUE TITLE
Installing from Github and adding new plugins

### ISSUE THREAD

**Issue by AndrMoura** [hvlads/django-ckeditor-5#124]
I followed the instructions on the README to set up django-ckeditor-5 on my project:

    cd your_root_project
    git clone https://github.com/hvlads/django-ckeditor-5.git
    cd django-ckeditor-5
    yarn install
    yarn run prod
    cd your_root_project
    python manage.py collectstatic

But when I run the last command, I get an error that says:  `ModuleNotFoundError: No module named 'django_ckeditor_5`. Obliviously I can install the package but doesn't that mean that any changes I make to the cloned repo are not reflected when I use the collectstatic command? I'm trying to install new plugins and want to modify your package.

**Comment by jlucero2** [comment]
Did you try adding 'django_ckeditor_5' to your list of INSTALLED_APPS in your settings.py? I don't know enough to know if that would help, just a thought.
