### ISSUE TITLE
Uploaded image src is path not link of the image

### ISSUE THREAD

**Issue by nareshban1** [hvlads/django-ckeditor-5#130]
![image](https://user-images.githubusercontent.com/49855000/225937102-53d5d1f7-8176-4492-91ad-716f1c300dd4.png)
 but i want src to have domain/media/imagename

**Comment by hvlads** [comment]
![image](https://github.com/hvlads/django-ckeditor-5/assets/10467081/3165d8d2-f6e4-4617-b54a-3afd112598ff)

You can do this, for example, like this.
