### ISSUE TITLE
Trouble integrating new plugins

### ISSUE THREAD

**Issue by aes256lamp** [hvlads/django-ckeditor-5#131]
This project implements everything I need in a text-editor right out of the box _except_ for a couple of things:

- [mentions](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html)
- [markdown](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html)

I tried following the [instructions given in the README.md](https://github.com/hvlads/django-ckeditor-5#installing-from-github) but I was getting clashes with my own `package.json`, and the python cannot handle dashes in paths either. A few hacks were attempted but I could never get the new plugins to be accepted and/or recognised.

Granted, frontend development ecosystems are not my wheel house. Python? Sure. But I really don't know my way around configs for frontend.

Summary:
- Can you provide some guidance on which areas of code need to be modified to handle new plugins?
- How should the project handle plugins that users want to install?

We can use myself and these plugins (or maybe just the mentions plugin because it has less dependencies) as a case study for successfully adding new plugins. 

Actionables:
- I'm willing and ready to write up the documentation for adding a new plugin. Seems only fair 🥲

**Comment by hvlads** [comment]
Hey there! I just wanted to let you know that I recently added the Mention plugin to the latest version of django-ckeditor-5. If you want to add any other plugin, just follow the instructions and make sure that the plugin version matches the version of ck-editor. It's a pretty straightforward process, so you shouldn't have any issues getting it set up.

**Comment by hvlads** [comment]
Good news. I installed Markdown by default in the latest version
