### ISSUE TITLE
DEFAULT_FILE_STORAGE is deprecated in favor of STORAGES["default"]

### ISSUE THREAD

**Issue by cclauss** [hvlads/django-ckeditor-5#138]
Django v4.2 release notes:
> The old DEFAULT_FILE_STORAGE and STATICFILES_STORAGE settings are deprecated as of this release.
> [ ... ]
> The DEFAULT_FILE_STORAGE setting is deprecated in favor of STORAGES["default"].

https://docs.djangoproject.com/en/4.2/releases/4.2

The following code must be modified to work around this deprecation:
https://github.com/hvlads/django-ckeditor-5/blob/bc84f0d14b55cf12a65c93a71f0e893a55743cd0/django_ckeditor_5/views.py#L21-L24

**Comment by hvlads** [comment]
Hi thanks for the issue report I fixed it in the latest version

**Comment by jsolly** [comment]
Does this impact using a custom storage as outlined in the readme?

**Comment by hvlads** [comment]
> Does this impact using a custom storage as outlined in the readme?

no, it doesn't impact, you can also use custom storage.
