### ISSUE TITLE
Removing plugin WordCount breaks CKEditor widget

### ISSUE THREAD

**Issue by digodude** [hvlads/django-ckeditor-5#140]
I tried to disable plugin WordCount, using 'removePlugins': 'wordcount'.  This breaks instantiating the CKEditor widget, in app.js, where specific WordCount config takes place.

`app.js:62:20 TypeError: t.some is not a function
    at c (plugincollection.js:234:48)`

**Comment by hvlads** [comment]
Hi thanks for the issue report I fixed it in the latest version
