### ISSUE TITLE
CKEditor 5 is GPL, not LPGL

### ISSUE THREAD

**Issue by guettli** [hvlads/django-ckeditor-5#15]
CKEditor 5 is GPL, not LPGL.

This means, if you create a commercial site with it, you might get legal troubles.

Are you aware if this?

See: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/license-and-legal.html

**Comment by hvlads** [comment]
> CKEditor 5 - это GPL, а не LPGL.
> 
> Это означает, что если вы создадите с его помощью коммерческий сайт, у вас могут возникнуть проблемы с законом.
> 
> Вы в курсе, если это?
> 
> См. [Https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/license-and-legal.html](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/license-and-legal.html)

What should I do in this case?
