### ISSUE TITLE
Problem with loading CKEditor5

### ISSUE THREAD

**Issue by bburan** [hvlads/django-ckeditor-5#16]
https://github.com/hvlads/django-ckeditor-5/blob/48b69997c012adf44a1737d16baa702b01ed5317/django_ckeditor_5/static/django_ckeditor_5/app.js#L25

I'm trying to setup this app on one of my websites. However, when I attempt to load the page containing the CKEditor5 field, I get an error in my browser developer console that's related to the line above.

The exact error is:
```
Uncaught TypeError: Cannot read property 'style' of null
    at HTMLDocument.<anonymous> (app.js:25)
```
It seems that, for some reason, `document.querySelector` is returning no matches. I don't understand the syntax in this particular selector, so I'm unable to debug this. Any pointers?

**Comment by hvlads** [comment]
`  Try adding this to the admin

  class Media:
        css = {
            'all': ['django_ckeditor_5/dist/styles.css',]
        }
        js = ('django_ckeditor_5/dist/bundle.js',)`

> https://github.com/hvlads/django-ckeditor-5/blob/48b69997c012adf44a1737d16baa702b01ed5317/django_ckeditor_5/static/django_ckeditor_5/app.js#L25
> 
> I'm trying to setup this app on one of my websites. However, when I attempt to load the page containing the CKEditor5 field, I get an error in my browser developer console that's related to the line above.
> 
> The exact error is:
> 
> ```
> Uncaught TypeError: Cannot read property 'style' of null
>     at HTMLDocument.<anonymous> (app.js:25)
> ```
> 
> It seems that, for some reason, `document.querySelector` is returning no matches. I don't understand the syntax in this particular selector, so I'm unable to debug this. Any pointers?

**Comment by bburan** [comment]
Ah, this only works in admin? I was trying to use this on a user-facing
page (i.e., non-admin).

Brad
