### ISSUE TITLE
How can I use all HTML tags and attributes in code mode editor?

### ISSUE THREAD

**Issue by twicros** [hvlads/django-ckeditor-5#163]
Hello. When I try to make some html in code mode, all things is filtred.

I try to add 'allowedContent': True, in settings.py in config CKE-5. But it is not work. This feature work only in CKE 4.

Help me please =)

**Comment by twicros** [comment]
I add to config this thing:

```
'htmlSupport': {
            'allow': [
                {
                    'name': '/.*/',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                }
            ]
        },
```

now its's work, I think.

Please confirm, is that correct?

**Comment by hvlads** [comment]
Yes, your code is correct. You can view an example at the following[ link](https://github.com/hvlads/django-ckeditor-5/blob/398dad99773bd4050da9accb44532b51483ec384/example/blog/blog/settings.py#L284).
