### ISSUE TITLE
Compatibility with django-modeltranslation

### ISSUE THREAD

**Issue by mikeromanov** [hvlads/django-ckeditor-5#17]
Hello! My website uses django-modeltranslation to support different languages. When I try to install django-ckeditor-5, I got the following error:

**django.core.exceptions.ImproperlyConfigured: CKEditor5Field is not supported by modeltranslation.**

Here is some additional information from the sunserver command:

File "/media/mike/Data/Websites/raptors/raptors/news/translation.py", line 7, in <module>
    translator.register(Article, ArticleTranslationOptions)
File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/translator.py", line 457, in register
    self._register_single_model(model, opts)
File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/translator.py", line 474, in _register_single_model
    add_translation_fields(model, opts)
File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/translator.py", line 149, in add_translation_fields
    translation_field = create_translation_field(
File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/fields.py", line 67, in create_translation_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: CKEditor5Field is not supported by modeltranslation.

Is it possible to use both django-ckeditor-5 and django-modeltranslation?

**Comment by hvlads** [comment]
Hi, I don't know, but you have - django.core.exceptions.ImproperlyConfigured: CKEditor5Field is not supported by modeltranslation.

> Hello! My website uses django-modeltranslation to support different languages. When I try to install django-ckeditor-5, I got the following error:
> 
> **django.core.exceptions.ImproperlyConfigured: CKEditor5Field is not supported by modeltranslation.**
> 
> Here is some additional information from the sunserver command:
> 
> File "/media/mike/Data/Websites/raptors/raptors/news/translation.py", line 7, in
> translator.register(Article, ArticleTranslationOptions)
> File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/translator.py", line 457, in register
> self._register_single_model(model, opts)
> File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/translator.py", line 474, in _register_single_model
> add_translation_fields(model, opts)
> File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/translator.py", line 149, in add_translation_fields
> translation_field = create_translation_field(
> File "/media/mike/Data/Websites/raptors-env/lib/python3.9/site-packages/modeltranslation/fields.py", line 67, in create_translation_field
> raise ImproperlyConfigured(
> django.core.exceptions.ImproperlyConfigured: CKEditor5Field is not supported by modeltranslation.
> 
> Is it possible to use both django-ckeditor-5 and django-modeltranslation?

**Comment by mikeromanov** [comment]
Thanks for the reply, Vladislav, but I don't get your point.

I know that django-modeltranslation doesn't currently support CKEditor5Field. What is the specifics of this field type? In django-ckeditor (based on CKEditor 4) there was RichTextField and RichTextUploadingField, both compatible with django-modeltranslation.

Now I had to return back to django-ckeditor, but I still hope to use django-ckeditor-5. Is there a way to achieve compatibility of these packages?

**Comment by hvlads** [comment]
try adding it to your settings.py
MODELTRANSLATION_CUSTOM_FIELDS = ('CKEditor5Field,)

**Comment by mikeromanov** [comment]
Thanks! I will try it.

**Comment by mikeromanov** [comment]
Thanks! It seems to work. However there are some other issues, I will describe them separately.
