### ISSUE TITLE
Forbidden (CSRF token missing or incorrect.): /ckeditor5/image_upload/

### ISSUE THREAD

**Issue by mikeromanov** [hvlads/django-ckeditor-5#18]
Hello again!

Thanks for helping me with the previous issue! Now the package seems to work, but not quite correctly. I'm having two different issues with different CBV views.

1. In my ArticleUpdateView it woks fine unless I'm trying to upload an image. Then I got following error:

Forbidden (CSRF token missing or incorrect.): /ckeditor5/image_upload/
WARNING 2020-12-01 12:21:16,314 log 43989 140116421977856 Forbidden (CSRF token missing or incorrect.): /ckeditor5/image_upload/
[01/Dec/2020 12:21:16] "POST /ckeditor5/image_upload/ HTTP/1.1" 403 14187

2. In my ArticleCreateView this error is also present. But, additionally, my **Submit** button doesn't work at all. It looks normally, but when it's pressed, nothing happens. If I change field type of my 'text' field to models.TextField, everything works fine.

As I understand, the first error is related to CSRF tokens, and the second error may be (possibly) related to form validity. But I don't know how to solve them. Please give me some ideas.

**Comment by hvlads** [comment]
Hello, this package is created for use in the admin panel
