### ISSUE TITLE
How to customize the list <ul> ?

### ISSUE THREAD

**Issue by JhonatanRian** [hvlads/django-ckeditor-5#181]
Is it somehow possible to make it so that when selecting a list, it comes with the predefined class attribute?
The only options I see are:
```
"list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            },
        },
```

**Comment by goapunk** [comment]
Hi @JhonatanRian You'd probably have to ask that over at the ckeditor5 repo, I don't think it's currently possible to add classes to most elements
