### ISSUE TITLE
How to have a FileUploader

### ISSUE THREAD

**Issue by nicolochiellini** [hvlads/django-ckeditor-5#184]
Hello
Anyone knows how to have a working File Uploader?
"UploadAdapter" and  "SimpleUploadAdapter" are listed but they seams not to work properly and there is no clue how make one works. 
Thank you

**Comment by goapunk** [comment]
@nicolochiellini are you talking about general file uploading or image uploading? Image uploading should work given that you configured your django project correctly. Providing your config and/or any error messages might help debugging

**Comment by HerrEich** [comment]
Image Uploading works just fine but i have no idea how to add the file uploading to the toolbar. are there specific keywords for the plugins to work in the toolbar like 'bulletedList', 'numberedList', etc.?

**Comment by goapunk** [comment]
@HerrEich Sadly there is no official support for file uploading in the free version of ckeditor5. You'd have to either get a license for CKBox or CKFinder. As we had the same problem we wrote our own plugin for it and made the appropriate changes to django-ckeditor-5. If general file uploading (as we had in the django-ckeditor 4 package ) is something @hvlads would be interested in I can open a PR here and we discuss it.

**Comment by nicolochiellini** [comment]
@goapunk it would be great! Me and my team will be glad to help you.

**Comment by goapunk** [comment]
@nicolochiellini @HerrEich  sorry for the delay, I opened #208 as a base to discuss
