### ISSUE TITLE
Django admin implement ckeditor-5

### ISSUE THREAD

**Issue by ekoabdulaziz2022** [hvlads/django-ckeditor-5#188]
Hi, I try to implement django-ckeditor-5,
after following the step, but I got this result. 
different from example "blog".

so, I can't use enter and pop up toolbar  bother me a lot

![image](https://github.com/hvlads/django-ckeditor-5/assets/106591685/3ee9ab39-3662-45c2-8db2-93babde5aefe)
![image](https://github.com/hvlads/django-ckeditor-5/assets/106591685/3e50f8ed-3b05-4cb0-a48e-e46264f49468)

please, help me.

**Comment by hvlads** [comment]
Hi, I see ck-editor 4 in your picture 🙂
