### ISSUE TITLE
Can't embed a YouTube video

### ISSUE THREAD

**Issue by jdbit** [hvlads/django-ckeditor-5#19]
I'm trying to insert a YouTube video link via the "Insert media" button in the editor. While the video preview showing up in the editor, it doesn't appear on the rendered page. Instead, it generates HTML like this:
`<figure class="media"><oembed url="https://www.youtube.com/watch?v=XXXXXXXX"></oembed></figure>`
According to the description, the MediaEmbed plugin is included in this package and it should work with YouTube links. Isn't it?
Thanks!

**Comment by jdbit** [comment]
Fixed by adding a line to the CKEDITOR_5_CONFIGS dict:
`'mediaEmbed': {'previewsInData': True},`

**Comment by 5antoshernandez** [comment]
Same here. Still not working after adding the additional line.

**Comment by jsolly** [comment]
I just checked my settings.py file and the line looks slightly different for me with `true` being lowercase and in quotes. Maybe try that?
```py
 "mediaEmbed": {"previewsInData": "true"}
 ```
