### ISSUE TITLE
How to use specialCharacters?

### ISSUE THREAD

**Issue by wangsy-ctrl** [hvlads/django-ckeditor-5#193]
How to add specialCharacters plugins to toolbar?

**Comment by goapunk** [comment]
the plugin is currently not shipped with this package, so you'd probably have to fork this repo and add the plugin here: https://github.com/hvlads/django-ckeditor-5/blob/master/django_ckeditor_5/static/django_ckeditor_5/src/ckeditor.js#L53

**Comment by hvlads** [comment]
Hi, @wangsy-ctrl  specialCharacters plugins  will be included in the latest version.
