### ISSUE TITLE
ListProperties dialog not showing up

### ISSUE THREAD

**Issue by 3continents** [hvlads/django-ckeditor-5#201]
While the lists plugin is installed and the settings include the list properties such as startIndex:True. The properties UX in the toolbar does not show up as it should in toolbar. You can see this working correctly here --

![image](https://github.com/hvlads/django-ckeditor-5/assets/153319272/a31b1add-dac7-47a6-84f3-2ad3576bf313)

Which is found at this URL: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html

In this implementation, that last part of list properties is missing. I have tested this in your example app as well. I have tried to add extra_plugins in the config

`        'extraPlugins': ','.join(
            [
               'ListProperties',
            ]
        ),`

This has not worked. I looked at the src directory and the ListProperties plugin is not added but apparently it needs to be to have this work in the classic editor.

https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists-installation.html#list-properties

It would be great if this can be added.

**Comment by goapunk** [comment]
@3continents would you like to open a PR for it? :)

**Comment by 3continents** [comment]
@goapunk I gave a quick try at recompiling the webpack adding "ListProperties" to ClassicEditor.builtinPlugins in django_ckeditor_5/static/django_ckeditor_5/src/ckeditor.js but nothing changed. I don't have any real experience with Webpack and tend to try to do everything in python and django. So, I am not sure if this is what required -- it feels like it is -- or what else I need to change to get this to work.

I will give another go and I succeed, I will create the PR. Sorry for the lack of experience on my side.

**Comment by goapunk** [comment]
@3continents sorry, I just had a look and the `ListProperties` plugin seems to be already included. So the reason it is not working for you must be a different one.

**Comment by goapunk** [comment]
@3continents It works for me with a config which includes the following:
```
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            },
        },
```
You can also see the `extends` config in the readme for an example.

**Comment by 3continents** [comment]
I have that in the extends property. It wasn't working for and this is why I tried to do it with your example app ... to see if I did something wrong in my implementation but it didn't work either. I will try again. If it works for you, please close. I will figure it out. Thanks a ton.
