### ISSUE TITLE
Height and width options + extra plugins

### ISSUE THREAD

**Issue by DaniSanchez01** [hvlads/django-ckeditor-5#204]
Hello! Thank you in advance for your time.

I'm trying to migrate from ckEditor 4 to ckEditor5 but I'm not finding where could I control the height/width of the widget in this project. Also, I've seen that there is no option yet to add extraplugins right? I would love to add the `emoji` plugin for my toolbar

**Comment by goapunk** [comment]
@DaniSanchez01 the height and with is now controlled via css, see https://ckeditor.com/docs/ckeditor5/latest/examples/how-tos.html#how-to-set-the-height-of-ckeditor-5

And yes, adding plugins dynamically is not supported yet.
