### ISSUE TITLE
Getting Reverse for 'ck_editor_5_upload_file' not found error

### ISSUE THREAD

**Issue by mohanraj-eee** [hvlads/django-ckeditor-5#205]
Reverse for 'ck_editor_5_upload_file' not found. 'ck_editor_5_upload_file' is not a valid view function or pattern name. I am getting this error when I am trying to integrate with the existing django application. what could be the possible issue here?

**Comment by stewic** [comment]
@mohanraj-eee did you find a solution to this? because I'm having the same problem

**Comment by goapunk** [comment]
@stewic did you include the path in your urls.py ?

**Comment by stewic** [comment]
@goapunk yes I've done that. I'm trying to use CKEditor5Widget in a form

**Comment by stewic** [comment]
if I got to http://127.0.0.1:8000/ckeditor5/image_upload/ I get a 404 and " The current path, ckeditor5/image_upload/, matched the last one. " message, but I get NoReverseMatch error if I try and load a view with a form which is referencing a CKEditor5Widget.
