### ISSUE TITLE
Add support for FullPage

### ISSUE THREAD

**Issue by JoeApo108** [hvlads/django-ckeditor-5#211]
Hi there,

my use case requires to have the FullPage feature imported from `import { FullPage } from '@ckeditor/ckeditor5-html-support';
` from official doc https://ckeditor.com/docs/ckeditor5/latest/features/html/full-page-html.html

the requered package is installed `@ckeditor/ckeditor5-html-support/` only add it to the `bundle.js`

Thx team.

**Comment by hvlads** [comment]
Hi, @JoeApo108. The FullPage feature will be included in the latest version.
