### ISSUE TITLE
Use custom build

### ISSUE THREAD

**Issue by omidshojaee** [hvlads/django-ckeditor-5#212]
I used CKEditor's builder to create a custom build with the plugins I need and now I have a ```ckeditor.js``` file. Is it possible to overwrite it over what comes with ```django-ckeditor-5``` library? If yes, what should I do?

**Comment by hvlads** [comment]
Hi, @omidshojaee 
cd your_root_project
git clone https://github.com/hvlads/django-ckeditor-5.git
cd django-ckeditor-5
replace ckeditor.js
yarn install
yarn run prod
cd your_root_project
python manage.py collectstatic
