### ISSUE TITLE
ImageCaption plugin support

### ISSUE THREAD

**Issue by mirodil1** [hvlads/django-ckeditor-5#217]
Hi there,

I'd like to request the addition of the `ImageCaption` plugin to this repository. The plugin lets us add captions to images by providing support for the `<figcaption>` element. 

Here are some additional details about the plugin:

Link to the plugin repository: [ImageCaption](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption-ImageCaption.html)
Brief description of the plugin's functionality: [image caption](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-captions.html) documentation.
If there are any concerns, I'd be happy to discuss them further.

Thanks for your time and consideration!

**Comment by goapunk** [comment]
hi @mirodil1 the `ImageCaption` plugin is already installed (however afaics not included in the toolbar config here), so you'd have to add `toggleImageCaption` as described in the links you added.
