### ISSUE TITLE
Add ability to overwrite user-provided file name

### ISSUE THREAD

**Issue by xSAVIKx** [hvlads/django-ckeditor-5#218]
It's frequently required to store files in e.g. subfolders or explicitly add some request-specific or user-specific information to the file name or the metadata.

It'd be great if you can provide a hook somewhere where the user is gonna get control over the file name + file params + request itself. I believe this can help solve multiple use cases and from what I see it should be OK to add such control somewhere here: https://github.com/hvlads/django-ckeditor-5/blob/a29f470681a151d0e72261e5e6543c6a847e033b/django_ckeditor_5/views.py#L75

**Comment by hvlads** [comment]
Hello! We've added a new feature that allows you to use your own logic for uploading images. Now, you can create your own view for uploading files and specify its name in the settings. For example:

```python
CK_EDITOR_5_UPLOAD_FILE_VIEW_NAME = "custom_upload_file"
path("upload/", custom_upload_file, name="custom_upload_file"),
```

This enables you to customize the file upload process according to your requirements and application logic.

This functionality will be available in the upcoming release.

**Comment by xSAVIKx** [comment]
Hey @hvlads. Thx for checking it out. While I do agree that it exposes the API I'd say this is the most low-level API one may use. You're basically reimplementing the whole upload view. This solves the problem but in the same way I already solved it locally - by reimplementing the API 🙂

IMO it'd be much more beneficial if one may add some specific logical overrides when needed instead of going all in and implementing the whole thing. But that's just a suggestion 🙂 thanks for making it configurable 👍

**Comment by hvlads** [comment]
Hello @xSAVIKx , if you have the code ready, could you please submit a pull request?  🙂
