### ISSUE TITLE
Problem with htmlEmbed due to rawHtml error

### ISSUE THREAD

**Issue by exotita** [hvlads/django-ckeditor-5#231]
Hi, first of all thanks for your amazing library.

I've a weird issue with the `htmlEmbed` feature in my project. I should mention that I'm not very familiar with JavaScript and its errors. When I use the `htmlEmbed` option, I get the following error:

`CKEditorError: attribute-operation-attribute-exists {"node":{"attributes":{},"name":"rawHtml"},"key":"value"}`

![Screenshot 2024-06-30 at 3 02 31 PM](https://github.com/hvlads/django-ckeditor-5/assets/3528426/a219184b-3153-43db-a49d-213b215476e6)

Additionally, any code I manually add inside `<div class="raw-html-embed">xxx</div>` in Source mode is automatically removed after saving!

Could you please check this issue or test it? 🙏

**Comment by Hamza-abughazaleh** [comment]
I have the same issue could anyone help us with it?
when I add the class="xxx" after saving the class attribute removed

**Comment by hvlads** [comment]
Hi,

Thank you for reaching out. Unfortunately, I am unable to assist with problems related to CKEditor 5, as my focus is on integrating it with Django. I recommend reaching out to the CKEditor 5 development team or their community for support.

Thank you for your understanding!
