### ISSUE TITLE
extraProviders for Youtube Shorts in Media Embed

### ISSUE THREAD

**Issue by jisoooh0202** [hvlads/django-ckeditor-5#244]
ckeditor5 has no regular expression for shorts for media embed. 
However, they allow other providers with [extraProviders](https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembedconfig-MediaEmbedConfig.html#member-extraProviders).

I was trying various way to add extraProviders in `CKEDITOR_5_CONFIGS`, but failed.

I asked on stackoverflow, but no one answered yet. 
https://stackoverflow.com/questions/78960825/django-ckeditor-5-media-embed-config-for-youtube-shorts

Have anyone done this? If so, please help.

**Comment by goapunk** [comment]
@jisoooh0202 I don't think it's currently possible as ckeditor expects the config to be valid javascript and not a string/python object. For now you'd have to fork this repository and add the providers directly in `app.js`. I assume we could improve the django config in the future to allow adding `extraProviders`.

**Comment by jisoooh0202** [comment]
@goapunk Thanks for your response. 
Just want to let you guys know that it is now possible to embed the shorts. 
ckeditor5 team made it work with my issue. 
https://github.com/ckeditor/ckeditor5/commit/2b74a8aeb69e8e01823d6cb1d0fb752f1480ee4d

But, it would be great to improve the django config in the future as you said. 
Thanks.
