### ISSUE TITLE
How does one add a custom plugin using this app?

### ISSUE THREAD

**Issue by meesterguyman** [hvlads/django-ckeditor-5#245]
We're coming from ckeditor 4, where we've built a custom youtube plugin, which when activated takes a video url and then embeds it in the text in the particular format required for our sites. I'd like to build the same thing for ckeditor 5, but from what I'm gathering from the docs, this would require me to install and use npm to make a separate build, which includes this new plugin. With the old editor, custom plugins could be added on the fly via javascript by replacing editor config, but not seeing anything about that for version 5, which would suggest that the particular build that this app uses wouldn't work for us. Am I mistaken? Is there a way to do what we need with this app, or no?

**Comment by jaredmdunn** [comment]
I just want to bump this issue because we are also interested in the possibility of incorporating custom CKEditor plugins while using django-ckeditor-5.

**Comment by hvlads** [comment]
Hi!

I wanted to let you know that I’ve included your code in the next release. Thank you!
