### ISSUE TITLE
Error Couldn't upload file: file.text/html; charset=utf-8

### ISSUE THREAD

**Issue by anton1k** [hvlads/django-ckeditor-5#246]
When I try to insert application/rtf content that contains a link, ckeditor tries to download the contents of the link and upload it to the server, which causes the error "Couldn't upload file: file.text/html; charset=utf-8" How can I make ckeditor not try to download, but simply insert rtf?
![изображение_2024-09-13_151104953](https://github.com/user-attachments/assets/a11b3d6f-bddf-4db9-96c2-c26a806f3ba7)

**Comment by goapunk** [comment]
@anton1k could you provide an example of that rtf content so we can test it?

**Comment by anton1k** [comment]
@goapunk You can simply create a link in the editor, copy it and paste it next to it, you get an error.

**Comment by goapunk** [comment]
opened https://github.com/hvlads/django-ckeditor-5/pull/247 which should hopefully fix it
