### ISSUE TITLE
Hangul Composition breakIng on Android Chrome

### ISSUE THREAD

**Issue by swyo** [hvlads/django-ckeditor-5#252]
Hi!

Thank you for your work on the plugin.

I would like to use this plugin as a text editor for Hangul on both Android and the web. However, I've noticed that it doesn't work well on Android. This issue is documented in the following link and has been fixed in CKEditor 5 version 43.0.0.

Related Issue: https://github.com/ckeditor/ckeditor5/issues/13693

I hope you can update the CKEditor 5 version to 43.0.0 or higher in the package.json file. (I am not familiar with JavaScript code, and I'm not sure how to make changes without affecting other parts of the code, so I would appreciate your help!)

### Plus
I attempted to customize build by replacing the following code:

https://github.com/hvlads/django-ckeditor-5/blob/9081d37ae5fe1078e25c72962b6a4e95d218c540/django_ckeditor_5/package.json#L20

with:

```
"@ckeditor/ckeditor5-engine": "^43.1.1", 
"@ckeditor/ckeditor5-editor-classic": "^43.1.1", 
```

and then build:

```
pip install .
```
However, the issue with Hangul composition breaking still persists. Please help me! 😢

**Comment by hvlads** [comment]
Hi!

Thank you for your message and for highlighting the issue with Hangul on Android. I wanted to let you know that I have already updated the CKEditor 5 version, and it will be available on PyPI soon.
