### ISSUE TITLE
JPG File Upload Failure

### ISSUE THREAD

**Issue by fish-not-phish** [hvlads/django-ckeditor-5#267]
I am attempting to upload a JPG file and it is not allowed, citing a 404 error. I have my settings configured in such a way:

CKEDITOR_5_ALLOW_ALL_FILE_TYPES = True
CKEDITOR_5_FILE_TYPES = [
    'jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff'
]

This should allow all files types, correct? I can upload any of the other files types without an issue.

**Comment by herotux** [comment]
same issue with ckeditor in uploading jpg format images its not working .i am get 404 error
but another formats is ok
and when i rename jpg to jpeg its uploaded without problem!

**Comment by fish-not-phish** [comment]
This appears to be fixed now. Unsure what the issue was, but I can now upload JPG files. May be due to updating the package.
