### ISSUE TITLE
Add custom plugin

### ISSUE THREAD

**Issue by erwanclx** [hvlads/django-ckeditor-5#274]
Hi,
I am currently implementing this package in my django app and it works as well, but for some configuration i am stuck.
Actuallay, i want to add non implementend plugin in my app.
I want to create one but before that, i try to simply import one existing.

Here is part of my config :

```python
...
'extends': {
    'toolbar': ['heading', '|', 'bold', 'italic', 'numberedList', 'bulletedList', '|', 'link',  'insertImage', 'insertTable'],
    'language': 'fr',
    'table': {
        'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
        'tableProperties', 'tableCellProperties' ],
    },
    'link': {
        'decorators': {
            'openInNewTab': {
                'mode': 'manual',
                'label': 'Ouvrir dans un nouvel onglet',
                'attributes': {
                    'target': '_blank',
                    'rel': 'noopener noreferrer',
                }
            }
        }
    },
    'extraPlugins': ','.join([
            'html5audio'
        ]),
```
i have the following error : `CKEditorError: plugincollection-plugin-not-found {"plugin":"html5audio"`
I can't figure where i need to put JS files for the plugin ?
I tried in my STATIC_ROOT (os.path.join(BASE_DIR, 'static')) in ckeditor/ckeditor/plugins/html5audio and some other folders but it is not working. Can you help me on that please ?

Thanks.

**Comment by goapunk** [comment]
Hi @erwanclx, it's currently not possible to include a plugin which is not installed in this repo already. To do that you would have to fork the repo and add your plugin [here](https://github.com/hvlads/django-ckeditor-5/blob/master/django_ckeditor_5/static/django_ckeditor_5/src/ckeditor.js)
