### ISSUE TITLE
Upload media Issue

### ISSUE THREAD

**Issue by onshadeep** [hvlads/django-ckeditor-5#31]
When I was uploaded image from backend django admin then the image is not getting upload on aws s3 media folder with name django-ckeditor-5/example.img. It is creating one folder with name django-ckeditor-5 on local server. but Not uploading on aws s3 media folder.

**Comment by onshadeep** [comment]
> When I was uploaded image from backend django admin then the image is not getting upload on aws s3 media folder with name django-ckeditor-5/example.img. It is creating one folder with name django-ckeditor-5 on local server. but Not uploading on aws s3 media folder.

**Comment by childon4god** [comment]
were you able to solve this problem? How

**Comment by childon4god** [comment]
how did you solve this problem
