### ISSUE TITLE
Image media is not uploading on AWS S3 

### ISSUE THREAD

**Issue by onshadeep** [hvlads/django-ckeditor-5#32]
When I was uploaded image from backend django admin then the image is not getting upload on aws s3 media folder with name django-ckeditor-5/example.img. It is creating one folder with name django-ckeditor-5 on local server. but Not uploading on aws s3 media folder.
I have putted both path but not working
` path(r'^ckeditor5/(?P<path>.*)/?$', include('django_ckeditor_5.urls')),`
` path("ckeditor5/", include('django_ckeditor_5.urls')),`
and tried with this one also
`re_path(r'^(?:.*)/?$', include('frontend.urls'))`

mine issue is exact same as issue #10 
Am I applying it in wrong way?

Click [here](https://stackoverflow.com/q/66993277/11360069) to check my question on stackoverflow.

**Comment by hvlads** [comment]
Hi, try it:
`pip install django-ckeditor-5==0.0.13`
in settings.py:
`CKEDITOR5_FILE_STORAGE='storages.backends.s3boto3.S3Boto3Storage'`
