### ISSUE TITLE
Bad Parse to database

### ISSUE THREAD

**Issue by imrobbyrc** [hvlads/django-ckeditor-5#34]
i have problem with v 0.0.13 , try to make bold text but i got this in database or view, it doesnt save a html tag i was try some tools.
![Screenshot from 2021-04-22 16-09-25](https://user-images.githubusercontent.com/25898417/115688214-244dfa00-a385-11eb-8524-ec59d5b7e4e4.png)

**Comment by imrobbyrc** [comment]
looks like its happend to your example too
![Screenshot from 2021-04-22 16-21-13](https://user-images.githubusercontent.com/25898417/115690008-d2a66f00-a386-11eb-95b2-980feecdf9fb.png)

**Comment by hvlads** [comment]
Thank you, I fixed this in version 0.0.14
