### ISSUE TITLE
File not found in static files - deployment fails

### ISSUE THREAD

**Issue by cdelacombaz** [hvlads/django-ckeditor-5#35]
Hi

I tried out django-ckeditor-5 for the first time today. In development mode it worked very well.

However, I tried to deploy on Heroku and got following error message:

> The CSS file 'django_ckeditor_5/src/custom_plugins/theme/titleform.css' references a file which could not be found:
  django_ckeditor_5/src/custom_plugins/theme/@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css

and in titleform.css I found follwing import, which can not be resolved.

>  @import "@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css";

My environment:
asgiref==3.3.4
certifi==2020.12.5
dj-database-url==0.5.0
Django==3.2
django-ckeditor-5==0.0.14
django-crispy-forms==1.11.0
django-on-heroku==1.1.2
gunicorn==20.1.0
Pillow==8.2.0
psycopg2-binary==2.8.6
pytz==2021.1
sqlparse==0.4.1
whitenoise==5.2.0

Any idea how I can solve this? Let me know if you need more information.

Thanks and best regards,

Cedric

**Comment by hvlads** [comment]
Hi, thank you for your issue. 
I will think about how to fix this in the next versions. 
For now, I can offer you the following solution:

in settings.py

from django.contrib.staticfiles.apps import StaticFilesConfig

class MyStaticFilesConfig(StaticFilesConfig):
    ignore_patterns = ['django_ckeditor_5/src/*']
    
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    ~~'django.contrib.staticfiles',~~
    'path_to_your.settings.MyStaticFilesConfig',
    'django_ckeditor_5',
    'articles'
]

**Comment by cdelacombaz** [comment]
Thanks a lot. That fixed it!
