### ISSUE TITLE
Is it possible to upload any file in a document?

### ISSUE THREAD

**Issue by iosifnicolae2** [hvlads/django-ckeditor-5#41]
Hi @hvlads

Is it possible to upload any file type in a document?

Thank you!

**Comment by hvlads** [comment]
What do you mean upload a file? Upload the file anywhere and insert a link to it in the document

**Comment by iosifnicolae2** [comment]
For example, I would like to upload a PDF file in the document the same way
we can upload pictures.

**Comment by hvlads** [comment]
I think you need a custom adapter to upload files. You also need to know if the ckeditor has the ability to upload pdf https://github.com/ckeditor/ckeditor5/issues/5999
