### ISSUE TITLE
Issue with new plugin

### ISSUE THREAD

**Issue by Asdonomar** [hvlads/django-ckeditor-5#44]
Hi, i have issue installing new plugins
i follow the instruction from other closed post:
https://github.com/hvlads/django-ckeditor-5/issues/21

Clone the repo
npm install
npm install @ckeditor/ckeditor5-word-count
https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html#installation

inside app.js
import WordCount from '@ckeditor/ckeditor5-word-count/src/wordcount';
passing WordCount as plugin value

and
npm run prod

the result is:
Uncaught CKEditorError: ckeditor-duplicated-modules

i did the same inside ckeditor.js i imported 
import WordCount from '@ckeditor/ckeditor5-word-count/src/wordcount';
and put WordCount in the ClassicEditor.builtinPlugins 
Same result

What im doing wrong?
Thanks

**Comment by Asdonomar** [comment]
I can respond by myself this is the step to fix the proble:.

1) I changed the version to match the others pluging.
2) import WordCount from '@ckeditor/ckeditor5-word-count/src/wordcount'; inside src/ckeditor.js
3) added WordCount in ClassicEditor.builtinPlugins = [ ... ] in  src/ckeditor.js
4) added the plugin settings inside app.js
5) npm install
6) npm run prod

And works fine
Thanks

**Comment by LetsCodeMore** [comment]
Do we need to clone the ckeditor5 repo for all steps?
