### ISSUE TITLE
Plugins usage

### ISSUE THREAD

**Issue by vagner-silva-getninjas** [hvlads/django-ckeditor-5#57]
Hi, sorry for opening an issue for that, but can you please tell how to set numbered list style types to have a menu to select from different types of styles, like numbers or roman?
Thanks in advance and sorry again for that.
Like that:
![image](https://user-images.githubusercontent.com/88545294/162213445-febd5a9b-6a3b-43d6-9ba2-7ac323071d43.png)

**Comment by hvlads** [comment]
Hi @vagner-silva-getninjas, thank you: that you noticed this problem, I fixed it in version 0.0.16

**Comment by vagner-silva-getninjas** [comment]
It works, thanks!!!!!
