### ISSUE TITLE
Add support of i18n url patterns

### ISSUE THREAD

**Issue by Dimitrioglo** [hvlads/django-ckeditor-5#58]
I had error because your package does not support locale prefix in urls, i fixed it this way:

```
urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

urlpatterns += i18n_patterns(
     // all my other urls
)
```

how it should works:

```
urlpatterns += i18n_patterns(
        path('ckeditor5/', include('django_ckeditor_5.urls')),
)
```

can you add i18n support, for example package nested admin, works perfectly when wrapped in i18n_patterns?

P.S. Awesome package!

**Comment by hvlads** [comment]
Hi @Dimitrioglo, thanks for noticing this problem, I fixed it in version 0.0.16
