### ISSUE TITLE
Ckeditor5 fails when using a widget on a field with django.forms.TextArea

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#62]
I was previously using [django-ckeditor](https://pypi.org/project/django-ckeditor/) which is built on ckeditor4 and am trying to migrate to ckeditor5 with this module.

It works perfectly on the admin page
![image](https://user-images.githubusercontent.com/9572232/170731346-27bd45e3-66f5-434c-85c0-ae04f6dea005.png)

But ckeditor5 does not load in my post-create route when there is a wiget attached to the form field. My goal in using the widget is to add a class to the field so that [line numbers](https://prismjs.com/plugins/line-numbers/) show up when using Prisim.js.

### forms.py
```py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "content",
        )

        widgets = {
            "content": forms.Textarea(attrs={"class": "line-numbers"}),
        }
```

### Workaround
If I remove the widget, ckeditor loads successfully.

```py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "content",
        )
```

### Environment
Python==3.9.7
django-ckeditor-5==0.1.0
django==3.2.13

### Discussion
I think this might be because this module was created to be used on the admin page as mentioned in [this issue](https://github.com/hvlads/django-ckeditor-5/issues/18).

**Comment by hvlads** [comment]
I have written an [example of using](https://github.com/hvlads/django-ckeditor-5/blob/918b6c41edb41b28816b2670b97b20c1e05bb88c/example/blog/articles/forms.py#L7) a widget in a form for you
