### ISSUE TITLE
403 Forbidden (CSRF token missing or incorrect.) when attempting to upload an image

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#63]
#### Steps to Reproduce 
1 - Add an image using the image option in the toolbar
2 - CSRF error
![2022-05-27_16-45-03 (1)](https://user-images.githubusercontent.com/9572232/170800790-ff148825-a16a-4fbf-b022-f26176b2d699.gif)

#### Workaround
Following [this SO answer](https://stackoverflow.com/questions/31618410/django-403-forbidden-csrf-token-missing-or-incorrect) I added the following to django_ckeditor_5.views

```py
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def upload_file(request):
    if request.method == "POST" and request.user.is_staff:
        form = UploadFileForm(request.POST, request.FILES)
        try:
            image_verify(request.FILES["upload"])
        except NoImageException as ex:
            return JsonResponse({"error": {"message": "{}".format(str(ex))}})
        if form.is_valid():
            url = handle_uploaded_file(request.FILES["upload"])
            return JsonResponse({"url": url})
    raise Http404(_("Page not found."))
```
and the image uploads sucessfully.

This also appears to be the same thing django-ckeditor is doing. See [line 136 in their view](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor_uploader/views.py)
```py
upload = csrf_exempt(ImageUploadView.as_view())
```

Environment
Python==3.9.7
django-ckeditor-5==0.1.0
django==3.2.13

**Comment by jsolly** [comment]
Should have read the previous issue that was closed. This package was created to use in the admin view.
https://github.com/hvlads/django-ckeditor-5/issues/18

**Comment by hvlads** [comment]
@jsolly This works now not only in the admin panel, apparently you just forgot to add csrf token to your request
https://docs.djangoproject.com/en/4.0/ref/csrf/

**Comment by hvlads** [comment]
You can also upload files from the frontend, but only with user.is_staff rights for now
