### ISSUE TITLE
Support ckeditor media upload folder setting to upload images to a specific folder

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#64]
#### Context 
Currently, it appears all images are going into the "/media." This works, but it would be really nice if we could change this to /media/uploads to keep things clean.

#### Current Behavior/Workaround
All images are saved in MEDIA_ROOT

#### Ideal behavior
Image uploads respect a setting set in the settings.py file such as CKEDITOR_5_UPLOAD_PATH

django-ckeditor has a pretty good approach in their [file upload section](https://github.com/django-ckeditor/django-ckeditor).

**Comment by hvlads** [comment]
In django_ckeditor_5 you can customize your storage class, 
I think this is a more flexible approach and gives you more options

[Here's](https://github.com/hvlads/django-ckeditor-5/commit/8f3e1f05f1e020685c169f9112952bc319acc6bb) how it might be for an example

Is this enough to solve your issue?

**Comment by jsolly** [comment]
Worked for me! THANKS @hvlads !!!!

**Comment by ddahan** [comment]
Works for me too, thanks!
I did not try in S3 yet, but I guess something like this would work:

```py
from django.core.files.storage import FileSystemStorage
from storages.backends.s3 import S3Storage

class FileUploadMixin:
    location = os.path.join(settings.MEDIA_ROOT, "upload")
    base_url = urljoin(settings.MEDIA_URL, "upload/")


class FileUploadS3Storage(FileUploadMixin, S3Storage):
    """Custom storage for django_ckeditor_5 images, located on S3"""


class FileUploadFileSystemStorage(FileUploadMixin, FileSystemStorage):
    """Custom storage for django_ckeditor_5 images, located on file system"""
```

In settings:

```py
if DEFAULT_FILE_STORAGE == "storages.backends.s3.S3Storage":
    CKEDITOR_5_FILE_STORAGE = "data.storage.FileUploadS3Storage"
else:
    CKEDITOR_5_FILE_STORAGE = "data.storage.FileUploadFileSystemStorage"
```
