### ISSUE TITLE
Remove unsafe-inline styles to respect a content security policy?

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#65]
#### Context 
I have a CSP ([Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)) for my app. When I turn off 'unsafe-inline' for styles, I see a lot of errors in the console
![image](https://user-images.githubusercontent.com/9572232/170852297-dadabeaa-cfd2-45a2-88fb-d3d37e560073.png)

#### Steps to reproduce
1 - Install [django-csp](https://django-csp.readthedocs.io/en/latest/installation.html)
2 - Add the following security policy in settings.py
```py
CSP_STYLE_SRC = "'self'"
```
3 - Start using CKEditor in edit mode
Lots of errors in console. Most functionality is maintained, but some things are broken (like image re-size).

#### Further Thoughts
According to the [CKEditor docs](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/csp.html):

- style-src 'self' 'unsafe-inline': 'unsafe-inline' is necessary for:
    -  webpage’s [style-loader](https://github.com/webpack-contrib/style-loader) to load the [editor UI styles](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html#styles-processing-and-bundling).

Note: You can [extract styles to a separate .css file](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source.html#option-extracting-css) during the editor building process and remove this directive.

- Certain editor content styles to work properly. For instance, you are going to need it if you want to enable such editor features as [font](https://ckeditor.com/docs/ckeditor5/latest/features/font.html) or [text alignment](https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html) or any other feature that uses inline style="..." attributes in the content.

I wonder if this is something we can do ourselves or if it requires work for the maintainers. I do see code in [config.webpack.js](https://github.com/hvlads/django-ckeditor-5/blob/master/django_ckeditor_5/webpack.config.js) that looks like it performs the CSS extraction.

**Comment by hvlads** [comment]
This error occurs because some ckeditor plugins use js to embed inline styles. You need to either opt out of using these plugins, or follow the recommendations in the console

**Comment by iamunadike** [comment]
this CSP is really an issue, you guys should have created a work around this issue , its been years, yet no fix, in django. this script injects an inline-script which loads or perhaps activates the editor yet nothing works. please help on this and get this fixed
