### ISSUE TITLE
Ckeditor does not look good in Django admin dark theme

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#66]
#### Context 
In Django 3.2 and higher, the admin page respects the theme of the system. In MacOS, if the theme is dark, the whole django admin UI is dark as well.

What seems to be happening is that the text color is being changed to white, but the background of ckeditor stays white as well.

#### Current Behavior
1 - Turn on Dark mode at the OS or browser level
2 - Visit the admin page and open a page with ckeditor
![image](https://user-images.githubusercontent.com/9572232/171546436-3d83a2d7-9a48-4e41-87ca-0bcd1ad7ba7b.png)
Text is white on white

#### Ideal behavior
Ckeditor is either not affected by theme change or it switches into its own dark mode.

### Workarounds
1 - If you highlight all the text and make it black, it makes it readable, but code blocks stay white
![image](https://user-images.githubusercontent.com/9572232/171546891-9e29bd96-0df9-467a-9bd7-a76890b98a9c.png)

2 - You could use the [django-non-dark-admin](https://pypi.org/project/django-non-dark-admin/) module to disable admin dark mode (This is what I did)

3 - You could disable dark theme by modifying the django admin css as explained in [this stackoverflow thread](https://stackoverflow.com/questions/68159768/disable-dark-mode-in-django-admin).

4 - Only use CKeditor outside of the admin page

5 - Use CKEDITOR_5_CUSTOM_CSS variable in settings.py to point to alternate CSS?

#### Other Resources
[CKeditor 5 Theme customization page](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html)

### Final thoughts
I've disabled the dark Django admin page for now, but any workarounds would be much appreciated!!!

### Environment
django-ckeditor-5==0.1.3
Python==3.9.7

**Comment by hvlads** [comment]
The CKEDITOR_5_CUSTOM_CSS settings constant is needed to add the styles you need.

Add to settings.py:

`CKEDITOR_5_CUSTOM_CSS = "custom.css"`

Add to custom.css:
```
.ck.ck-editor {
    color: black;
}

```

**Comment by hvlads** [comment]
![image](https://user-images.githubusercontent.com/10467081/171623219-7244513b-be43-49e1-9663-73541caf78ea.png)

**Comment by jsolly** [comment]
For anyone reading this, I followed these steps to get the custom CSS working.
1 - Copy [custom.css](https://github.com/hvlads/django-ckeditor-5/blob/master/example/blog/static_files/custom.css) into your static folder
2 - Change this line in your settings.py assuming STATIC_URL refers to where your static files live (such as /static/)
```py
CKEDITOR_5_CUSTOM_CSS = os.path.join(STATIC_URL, "django_ckeditor_5/ckeditor_custom.css")
```
