### ISSUE TITLE
change language of ckeditor

### ISSUE THREAD

**Issue by masiha972** [hvlads/django-ckeditor-5#72]
hey there i have 2 questions:

1)how to change language of ckeditor?

2)how to change type, version of ckeditor?

Thanks!

**Comment by hvlads** [comment]
Hi @masiha972 ,

1) I added languages support in version 0.1.6, just change the [settings.py ](https://github.com/hvlads/django-ckeditor-5/blob/976e9fbc490bf6441c2d7a805c56dc2b69c923ec/example/blog/blog/settings.py#L161)

2) Currently only Classic editor is supported, but I'll think about how to improve it.
