### ISSUE TITLE
support ImageInsert plugin

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#76]
#### Context 
Currently, we have the ability to upload images using the imageUpload toolbar item. Unfortunately, this does not work when using images that are hosted elsewhere and you do not want to upload a copy.

If you add `imageUpload` to the toolbar, you can upload images, but there is no way to reference the image via URL.
![image](https://user-images.githubusercontent.com/9572232/182043158-968da773-a0c8-4255-b16a-90508993a805.png)

#### Workaround
You can add the image manually using a <img> tag and enable the source toolbar item.
< image src="..." > example image < / img >

But this is a lot of extra typing.

#### Ideal behavior
According to the [CKeditor5 documentation](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/images-inserting.html) if we install the `ImageInsert` extension, we can replace imageUpload with insertImage. This toolbar item has an extra dropdown next to the image icon that lets you add an image via URL
![image](https://user-images.githubusercontent.com/9572232/182043265-2cadc02b-f8ec-4a5c-b08f-03959c770192.png)

Once this is added, we should be able to just replace imageUpload with insertImage in our toolbar configuration within settings.json

**Comment by hvlads** [comment]
Hi @jsolly I fixed this in the version django-ckeditor-5 0.1.7

**Comment by jsolly** [comment]
Thanks @hvlads. Works for me in 0.1.8
![image](https://user-images.githubusercontent.com/9572232/184070576-13e3a123-1fc2-43e2-9beb-b34b1b4692b4.png)
