### ISSUE TITLE
Mention how to add ckeditor5 styles to the front end of your app

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#78]
#### Context 
In order to get ckeditor5 CSS styles into the front end (like a post detail route), you need to download the CSS file from the [CKeditor5 docs.](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html#the-full-list-of-content-styles)

Then you include it on your page
```html
<link rel="stylesheet" href="path/to/assets/content-styles.css" type="text/css">
```

Finally, you want to make sure that the ck-content class is included in the parent element that contains your ckeditor5 content. For me, it was something like this:

```html
<div class="ck-content">
    <p>{{ post.content|safe }}</p>
</div>
```
I don't think this is obvious and should be included in an example or in the readme.

**Comment by hvlads** [comment]
Hi, @jsolly can you make a pull request for this issue?

**Comment by hvlads** [comment]
Hi, @jsolly would you like to make a pull request for this issue?
