### ISSUE TITLE
0.1.8 Can be used, 0.1.9 No module named 'django_ckeditor_5'

### ISSUE THREAD

**Issue by ddworld2** [hvlads/django-ckeditor-5#91]
root@cdasia:/home# pip install django-ckeditor-5
Requirement already satisfied: django-ckeditor-5 in /usr/local/lib/python3.9/dist-packages (0.1.9)
Requirement already satisfied: Django==4.1 in /usr/local/lib/python3.9/dist-packages (from django-ckeditor-5) (4.1)
Requirement already satisfied: Pillow==9.0.1 in /usr/local/lib/python3.9/dist-packages (from django-ckeditor-5) (9.0.1)
Requirement already satisfied: asgiref<4,>=3.5.2 in /usr/local/lib/python3.9/dist-packages (from Django==4.1->django-ckeditor-5) (3.5.2)
Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.9/dist-packages (from Django==4.1->django-ckeditor-5) (0.4.2)

root@cdasia:/home# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import django_ckeditor_5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'django_ckeditor_5'

**Comment by ddworld2** [comment]
Debian 5.10.140-1

**Comment by jsolly** [comment]
I am experiencing the same issue. 0.1.8 works. 0.1.9 I get that error that the module cannot be found.

**Comment by hvlads** [comment]
Hi @jsolly, @ddworld2 , thanks for the error message, try the latest version

**Comment by jsolly** [comment]
@hvlads 0.2.0 works as expected. Thx
