### ISSUE TITLE
Check the correct settings.CKEDITOR_5_CONFIGS 'comment' 

### ISSUE THREAD

**Issue by pujanrajrai** [hvlads/django-ckeditor-5#95]
Greetings everyone

i was trying to implement django ckeditor 5. It works completly fine on django admin but when i implement on django templates it show me ----> Check the correct settings.CKEDITOR_5_CONFIGS 'comment'  <---- error. can you please help me resolve this error.

<img width="1130" alt="Screen Shot 2022-09-17 at 3 21 38 PM" src="https://user-images.githubusercontent.com/70184988/190850383-f8b639bd-2385-49b9-8389-2077c4a44ad5.png">

**Comment by hvlads** [comment]
I think you need to check the correct settings.CKEDITOR_5_CONFIGS 'comment'
