### ISSUE TITLE
Set link into image.

### ISSUE THREAD

**Issue by jemalpartida** [hvlads/django-ckeditor-5#96]
Hi, my apologies, certainly this question is not an issue. I'm trying set a link into image and when I select the image, the link icon is disabled and doesn't work:

![Captura de pantalla de 2022-09-20 15-45-36](https://user-images.githubusercontent.com/65556663/191276045-824c2b7b-01b0-4f94-968a-46b63890c876.png)

Would be possible a behaviour like this?
![Captura de pantalla de 2022-09-20 15-45-10](https://user-images.githubusercontent.com/65556663/191276522-9ed7b77c-c3ca-473d-a22f-4e32d85bd885.png)

I'm using django-ckeditor-5 version 0.1.8
Do I need any extra configuration?

Best regards,
  Jorge.

**Comment by jsolly** [comment]
Not sure if there is a way to use the built-in link functionality like that on an image.

A workaround would be to add the `sourceEditing` tool to your toolbar. Once that is added, you can click on it to see the raw html. Then all you have to do is something like this:

```html
      <a href="https://www.qries.com/">
         <img alt="Qries" src="https://www.qries.com/images/banner_logo.png"
         width=150" height="70">
      </a>
 ```

Check the readme of this repo to see how to add the `sourceEditing` plugin.

Hope that helps!
