### ISSUE TITLE
How to add new plugins like HtmlEmbed?

### ISSUE THREAD

**Issue by LetsCodeMore** [hvlads/django-ckeditor-5#97]
Can you please share step by step procedure for adding new plugins? I tried but not able to add the new plugins. Even I tried the online builder of ckeditor5. (https://ckeditor.com/ckeditor-5/online-builder/) :(

**Comment by LetsCodeMore** [comment]
I replaced both bundle.js and bundle.js.map with new files and added new plugins in src/ckeditor.js but no results.

**Comment by hvlads** [comment]
You can add plugins in [this](https://github.com/hvlads/django-ckeditor-5/blob/master/django_ckeditor_5/static/django_ckeditor_5/src/ckeditor.js) file. Then run  `npm run prod`
