### ISSUE TITLE
Changing the default HTML for uploaded images

### ISSUE THREAD

**Issue by varus17** [hvlads/django-ckeditor-5#98]
Hi,

Would it be possible to replace the default HTML code that displays the images? I need to implement a bootstrap modal for images to open them full screen. Currently, the saved images are displayed as:

```
<figure class="image image-style-align-center image_resized" style="width:100%;"><img src="URL_TO_IMAGE"></figure>
```

And I would like to add a bootstrap modal for each image. Or an alternative would be making the images clickable to open in a new tab. Thank you!

**Comment by hvlads** [comment]
Hi, I think you need to contact the developers of ckeditor5 with this question. Maybe [here](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html) you can find something useful for yourself
