### ISSUE TITLE
[Accessibility] - Enable caption for HTML tables

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#99]
#### Context 
Table captions are recommended for sighted and unsighted users. This allows them to quickly understand what the table is about without having to start reading/listening through the data of the table.
See -> https://www.w3.org/WAI/tutorials/tables/caption-summary/

#### Ideal behavior
Captions can be turned on/off. This is how it works in the [CKEditor5 demo editor.](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)
![image](https://user-images.githubusercontent.com/9572232/195719482-0d40f9cc-95c5-4132-b2e3-399dadbf904c.png)

#### Implementation Notes
According to the [CKEDitor5 docs](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-caption-2), this can be 'turned on' by adding the `tableCaption` plugin.

**Comment by hvlads** [comment]
I added the code and in the next release this functionality will appear
